services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HeimrichHannot\AdvancedDashboardBundle\EventListener\Contao\ParseTemplateListener: ~
  HeimrichHannot\AdvancedDashboardBundle\Generator\VersionsListGenerator: ~